sudo: required
language: java
jdk: oraclejdk8
dist: trusty

env:
  - TARGET=ui
  - TARGET=service/cart
  - TARGET=service/user
  - TARGET=repository/order
  - TARGET=repository/cart
  - TARGET=repository/product
  - TARGET=repository/user

install:
  - "./gradlew clean jar"

script:
  - "COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check"

deploy:
  - provider: script
    script: echo "WIP"
    on:
      all_branches: true
