sudo: required
language: java
jdk: oraclejdk8
dist: trusty

env:
  - JDK_VERSION=oraclejdk8
  - JDK_VERSION=oraclejdk9

install:
  - "./gradlew clean jar"

stages:
  - test

jobs:
  include:
    - stage: test
      name: "Check jdk8 - ui"
      install: skip
      script:
      - "COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/$TARGET check"
      env:
        - JDK_VERSION=oraclejdk8
        - COVERAGE=0.5
        - TARGET=ui
    - stage: test
      name: "Check jdk8 - service/cart"
      install: skip
      script:
      - "COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/$TARGET check"
      env:
        - JDK_VERSION=oraclejdk8
        - COVERAGE=0.5
        - TARGET=service/cart


deploy:
  - provider: script
    script: echo "WIP"
    on:
      all_branches: true
