sudo: required
dist: trusty
services:
  - docker
language: java
jdk:
- oraclejdk8
- oraclejdk9
env:
  matrix:
  - COVERAGE=0.5 TARGET=ui
  - COVERAGE=0.5 TARGET=service/cart
  - COVERAGE=0.5 TARGET=service/user
  - COVERAGE=0.36 TARGET=repository/order
  - COVERAGE=0.5 TARGET=repository/cart
  - COVERAGE=0.5 TARGET=repository/product
  - COVERAGE=0.31 TARGET=repository/user
  global:
  - secure: BfqBouRKaPRqS7N42025viVs3AxI4dhQTA5uIVJDfAt5q1CkZ9fZUXeVGsXA0SG2ErfJN0hzWUFqTUYl4iTGAF922np72bjXBerqeLYAVpRI/xcrX9xCWUDujKgNdjiHtpB9pQ5mfeyjdewqQARglsTT5CrAkljkhVi/YBS2OnGTrjPT2yTEbWzRXszBkRT9PrW3WH2jdIrz3RYSQM4IEVQLa4b/kLJyiVqE4iGA2ItzzU85XH+SgtA7ituzdhiWeuYQElwDx5A1m1+g09gpI+iXUUW9ANLlBehy3mYwt8y2wURmyy91GMgMMGvAMZJPYLATo1/rqaF6HwcwxVml/n7YPNay5LOl+3M1AWpTDPhx73g3evSzkVLzAeXPKF2a456kicRHwDsZsUuhngdZcOYo2FtK3da7ON4jAtdapZ9ZwvmLlB/DEJN3sSZlmNr9Ggdx05TtIHyiD9D6p1RgIF2xzy7z5X+i62Iltsmq62cDSAVNR/RetGOK5Y8CURrpz5caCuExsaF8YrfDuXiymL0D7IdaHnG2WQMqcIzHQnA0MIR1sQ1R3zvjXzFZ79cwJvtQ6HDTR78FdDjNsQPaoSd6hyBKHqvn3/XpgkTMcW7OAPSb+4qNfAg+DYEKWcwA3eH8VUkAXwDqVXKQe5UNKvKJ2GBn7syJV6uj2FIr3ls=
  - secure: P3aLT/fhVCOK8xr4eLby5cfvv/Ew4PFv+D70dvR0/vkaUgbYA2h39Fp3fWMny+aBnHgcmlBxZ8oXrtfqZn6/K+WubALWANPs967v6eqIOO9L8vKEBlE2V/5d/MMdBstSG8GNMg1S98+aW8uaxo60+uPIwOp77bxZf6dlgsorknbHSTJ1LzUhgFeMC5jTB/PenQ5FPBa/GWpuyuMZ80cVqT0j/x+11FdE10/7J/A61fkfUXqo7W7eJJV9tkKLCvbZY6T4BfzocoXiQwiD4TBH2s7xiCS5y1pFrKiRfbfS07wB7ocJY/58MjoA9LF6szAX9zNxrhGn5BtK11+9z0lDBrChhcn7sjlZJEb8VnvTeKzls4cRxCa3Bn+r0RO2uetSXUJLoDF6y+IQzi+6zxT1AI4P7U1CA4kNgxs4WgSrUpuSzrPsN4Nfq+7EVGNRdOhJPM+O/ILLZKPnP2Q1RG4bTgFsHmTADWs6hPKraPqF1PwN7ymfBTgPd+FqrY6kW7EaGCDZoVCCt+LpulY9jIt628uQOADcAgn4WY4aXybXKtzAYkR3EYYTcRrkasVHNCD5IMOXHV7a3oESW7pXPCqK9KgZFL9zkEeo0lv3372SEIKyLPiRqjXOCEj91cquzZYyS+E5L9EQF7kKfX3tiampHJG/UOjzAdjotf9K7751ffA=
install:
- "./gradlew clean jar"
script:
- COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
deploy:
- provider: script
  script:
    - bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin"
    - echo "WIP"
  on:
    all_branches: true
