sudo: required
language: java
jdk: oraclejdk8
dist: trusty

env:
  - COVERAGE=$COVERAGE_UI TARGET=ui
  - COVERAGE=$COVERAGE_SERVICE_CART TARGET=service/cart
  - COVERAGE=$COVERAGE_SERVICE_USER TARGET=service/user
  - COVERAGE=$COVERAGE_REPOSITORY_ORDER TARGET=repository/order
  - COVERAGE=$COVERAGE_REPOSITORY_CART TARGET=repository/cart
  - COVERAGE=$COVERAGE_REPOSITORY_PRODUCT TARGET=repository/product
  - COVERAGE=$COVERAGE_REPOSITORY_USER TARGET=repository/user

install:
  - "./gradlew clean jar"

script:
  - "COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/$TARGET check"

deploy:
  - provider: script
    script: echo "WIP"
    on:
      all_branches: true
